{% set version = "0.6.0" %}

package:
  name: pyjokes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjokes/pyjokes-{{ version }}.tar.gz
  sha256: 08860eedb78cbfa4618243c8db088f21c39823ece1fdaf0133e52d9c56e981a5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyjokes
  requires:
    - pytest

about:
  home: https://github.com/pyjokes/pyjokes
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENCE.txt'
  summary: One line jokes for programmers (jokes as a service)

extra:
  recipe-maintainers:
    - ocefpaf
