{% set version = "0.7.2" %}

package:
  name: pyjokes
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pyjokes/pyjokes-{{ version }}.tar.gz
  sha256: 1a0dab5bfd30deee547055ebf26b2073b4dd10b708311b4c9bdf6ccb743d5821

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - pyjokes
  requires:
    - pytest

about:
  home: https://github.com/pyjokes/pyjokes
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENCE.txt'
  summary: One line jokes for programmers (jokes as a service)

extra:
  recipe-maintainers:
    - ocefpaf
