travis:
  secure:
    BINSTAR_TOKEN: awlNAAAdTAyNzqdsPBwCnYJPk8x+Z9g+4Xs7kcqgLH3mkoShC2yCQGzl9sQFI5E5s3Lm3yRTKmGFJzjyp7GtUmN8Td8rBxAUqZUC3JrbS3SP/ivYpUmsitHeYXRkSjOuNbjN1S/QLUJLiuAxDBVsx0LLScZgsO93jPK929OUHIZlZzmD/5GJwHktAuhM0DrzZZjqI5wl66yAX5bXYMEF2X3XEraM02cfQVTXVDnJ0BqqRcJAjMpAtUL3drQu3QTRZakp0vR7obKZxsonjid9GJ/shlcR79PsuzsoMmAS/GK/awXv6Agke01CF1UaarB7gFn6kLPTjmvfmHgS7WFBcVdsGFm//x93qvnUS4lO6mXD8spSWX208ZKj0tCB7vlfk7oLZQQF3rjAaGXzJlD5vpHNc2ibSdIZZscuTrGd/PQISeNRCly9P8S6c0JOhAGSb3IZc/wVByeeFsX2QVk73ej+kw6a2iMbgyb5+HhUr5mgQPXiWwrupxZX1sol9gbEWRu+6Ds4ckCJ4GfaXhMzFkFJJ7mWe0QxBeK+lzR8hWZ3N5Juu3iwEPlmRWsL8DeO1YkFdVnuur4tBEUZmN/vOCJqh+5II5bf4OF2orl4tXHh7HlIzBe+fR40QW92mRiblYarRzhVpeeJEE1fHkGNJXXZE1I5YY4WIGCNBUUfs+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
